// Code generated by go-swagger; DO NOT EDIT.

// Package restapi OpeinAPI specs for test project
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: 1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
