// Code generated by go-swagger; DO NOT EDIT.

package pizzas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPizzasHandlerFunc turns a function with the right signature into a get pizzas handler
type GetPizzasHandlerFunc func(GetPizzasParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPizzasHandlerFunc) Handle(params GetPizzasParams) middleware.Responder {
	return fn(params)
}

// GetPizzasHandler interface for that can handle valid get pizzas params
type GetPizzasHandler interface {
	Handle(GetPizzasParams) middleware.Responder
}

// NewGetPizzas creates a new http.Handler for the get pizzas operation
func NewGetPizzas(ctx *middleware.Context, handler GetPizzasHandler) *GetPizzas {
	return &GetPizzas{Context: ctx, Handler: handler}
}

/*
	GetPizzas swagger:route GET /pizzas pizzas getPizzas

Get all the pizzas
*/
type GetPizzas struct {
	Context *middleware.Context
	Handler GetPizzasHandler
}

func (o *GetPizzas) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPizzasParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
