// Code generated by go-swagger; DO NOT EDIT.

package pizzas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPizzasOKCode is the HTTP code returned for type GetPizzasOK
const GetPizzasOKCode int = 200

/*
GetPizzasOK Success

swagger:response getPizzasOK
*/
type GetPizzasOK struct {
}

// NewGetPizzasOK creates GetPizzasOK with default headers values
func NewGetPizzasOK() *GetPizzasOK {

	return &GetPizzasOK{}
}

// WriteResponse to the client
func (o *GetPizzasOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetPizzasBadRequestCode is the HTTP code returned for type GetPizzasBadRequest
const GetPizzasBadRequestCode int = 400

/*
GetPizzasBadRequest Invalid request

swagger:response getPizzasBadRequest
*/
type GetPizzasBadRequest struct {
}

// NewGetPizzasBadRequest creates GetPizzasBadRequest with default headers values
func NewGetPizzasBadRequest() *GetPizzasBadRequest {

	return &GetPizzasBadRequest{}
}

// WriteResponse to the client
func (o *GetPizzasBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

/*
GetPizzasDefault Error

swagger:response getPizzasDefault
*/
type GetPizzasDefault struct {
	_statusCode int
}

// NewGetPizzasDefault creates GetPizzasDefault with default headers values
func NewGetPizzasDefault(code int) *GetPizzasDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPizzasDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get pizzas default response
func (o *GetPizzasDefault) WithStatusCode(code int) *GetPizzasDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get pizzas default response
func (o *GetPizzasDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetPizzasDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
